//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace RobotWebApp.Robot
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IRobotController
    {

        /// <summary>
        /// Create a new empty board
        /// </summary>


        /// <returns>successful operation</returns>

        System.Threading.Tasks.Task<Board> CreateBoardAsync(Dimensions body);

        /// <summary>
        /// Get a list of boards
        /// </summary>

        /// <returns>successful operation</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Board>> GetAllBoardsAsync();

        /// <summary>
        /// Get a board by id
        /// </summary>

        /// <param name="boardId">the board to get</param>

        /// <returns>successful operation</returns>

        System.Threading.Tasks.Task<Board> GetBoardByIdAsync(int boardId);

        /// <summary>
        /// delete a board
        /// </summary>

        /// <remarks>
        /// deletes a board and all related robots
        /// </remarks>

        /// <param name="boardId">the board to get</param>

        /// <returns>Successful operation</returns>

        System.Threading.Tasks.Task DeleteBoardAsync(int boardId);

        /// <summary>
        /// Get robots on a board
        /// </summary>

        /// <remarks>
        /// gets all the robots related to a board
        /// </remarks>

        /// <param name="boardId">the board to get robots from</param>

        /// <returns>successful operation</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Robot>> GetRobotsOnBoardAsync(int boardId);

        /// <summary>
        /// Spawn a new robot on the board
        /// </summary>

        /// <param name="boardId">the board to spawn the robot on</param>


        /// <returns>Robot spawned</returns>

        System.Threading.Tasks.Task<Robot> RobotAsync(int boardId, Robot body);

        /// <summary>
        /// get all robots that exist
        /// </summary>

        /// <returns>successful operation</returns>

        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Robot>> GetAllRobotsAsync();

        /// <summary>
        /// get robot by id
        /// </summary>

        /// <param name="robotId">the robot to get</param>

        /// <returns>Successful operation</returns>

        System.Threading.Tasks.Task<Robot> GetRobotByIdAsync(int robotId);

        /// <summary>
        /// delete a robot
        /// </summary>

        /// <remarks>
        /// deletes a robot
        /// </remarks>

        /// <param name="robotId">the robot to delete</param>

        /// <returns>Successful operation</returns>

        System.Threading.Tasks.Task DeleteRobotAsync(int robotId);

        /// <summary>
        /// issue move command to robot
        /// </summary>

        /// <param name="robotId">the robot to move</param>

        /// <param name="body">Move command</param>

        /// <returns>Successful operation</returns>

        System.Threading.Tasks.Task<CoordinateDirection> MoveRobotAsync(int robotId, string body);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("v1")]

    public partial class MyResourceController : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IRobotController _implementation;

        public MyResourceController(IRobotController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Create a new empty board
        /// </summary>
        /// <returns>successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("board")]
        public System.Threading.Tasks.Task<Board> CreateBoard([Microsoft.AspNetCore.Mvc.FromBody] Dimensions body)
        {

            return _implementation.CreateBoardAsync(body);
        }

        /// <summary>
        /// Get a list of boards
        /// </summary>
        /// <returns>successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("board")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Board>> GetAllBoards()
        {

            return _implementation.GetAllBoardsAsync();
        }

        /// <summary>
        /// Get a board by id
        /// </summary>
        /// <param name="boardId">the board to get</param>
        /// <returns>successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("board/{boardId}")]
        public System.Threading.Tasks.Task<Board> GetBoardById(int boardId)
        {

            return _implementation.GetBoardByIdAsync(boardId);
        }

        /// <summary>
        /// delete a board
        /// </summary>
        /// <remarks>
        /// deletes a board and all related robots
        /// </remarks>
        /// <param name="boardId">the board to get</param>
        /// <returns>Successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("board/{boardId}")]
        public System.Threading.Tasks.Task DeleteBoard(int boardId)
        {

            return _implementation.DeleteBoardAsync(boardId);
        }

        /// <summary>
        /// Get robots on a board
        /// </summary>
        /// <remarks>
        /// gets all the robots related to a board
        /// </remarks>
        /// <param name="boardId">the board to get robots from</param>
        /// <returns>successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("board/{boardId}/robot")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Robot>> GetRobotsOnBoard(int boardId)
        {

            return _implementation.GetRobotsOnBoardAsync(boardId);
        }

        /// <summary>
        /// Spawn a new robot on the board
        /// </summary>
        /// <param name="boardId">the board to spawn the robot on</param>
        /// <returns>Robot spawned</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("board/{boardId}/robot")]
        public System.Threading.Tasks.Task<Robot> Robot(int boardId, [Microsoft.AspNetCore.Mvc.FromBody] Robot body)
        {

            return _implementation.RobotAsync(boardId, body);
        }

        /// <summary>
        /// get all robots that exist
        /// </summary>
        /// <returns>successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("robot")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Robot>> GetAllRobots()
        {

            return _implementation.GetAllRobotsAsync();
        }

        /// <summary>
        /// get robot by id
        /// </summary>
        /// <param name="robotId">the robot to get</param>
        /// <returns>Successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("robot/{robotId}")]
        public System.Threading.Tasks.Task<Robot> GetRobotById(int robotId)
        {

            return _implementation.GetRobotByIdAsync(robotId);
        }

        /// <summary>
        /// delete a robot
        /// </summary>
        /// <remarks>
        /// deletes a robot
        /// </remarks>
        /// <param name="robotId">the robot to delete</param>
        /// <returns>Successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpDelete, Microsoft.AspNetCore.Mvc.Route("robot/{robotId}")]
        public System.Threading.Tasks.Task DeleteRobot(int robotId)
        {

            return _implementation.DeleteRobotAsync(robotId);
        }

        /// <summary>
        /// issue move command to robot
        /// </summary>
        /// <param name="robotId">the robot to move</param>
        /// <param name="body">Move command</param>
        /// <returns>Successful operation</returns>
        [Microsoft.AspNetCore.Mvc.HttpPut, Microsoft.AspNetCore.Mvc.Route("robot/{robotId}/move")]
        public System.Threading.Tasks.Task<CoordinateDirection> MoveRobot(int robotId, [Microsoft.AspNetCore.Mvc.FromBody] string body)
        {

            return _implementation.MoveRobotAsync(robotId, body);
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Dimensions
    {

        /// <summary>
        /// number of rows on the board
        /// </summary>
        [Newtonsoft.Json.JsonProperty("rows", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(2L, 4294967295L)]
        public long Rows { get; set; }

        /// <summary>
        /// number of rows on the board
        /// </summary>
        [Newtonsoft.Json.JsonProperty("columns", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [System.ComponentModel.DataAnnotations.Range(2L, 4294967295L)]
        public long Columns { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Board : Dimensions
    {

        /// <summary>
        /// Identifier for use in requests
        /// </summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long Id { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Robot
    {

        /// <summary>
        /// Identifier for use in requests
        /// </summary>
        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long Id { get; set; }

        [Newtonsoft.Json.JsonProperty("coordinates", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CoordinateDirection Coordinates { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// Coordinates of an object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Coordinate
    {

        /// <summary>
        /// x-coordinate
        /// </summary>
        [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(1L, 4294967295L)]
        public long X { get; set; }

        /// <summary>
        /// y-coordinate
        /// </summary>
        [Newtonsoft.Json.JsonProperty("y", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Range(1L, 4294967295L)]
        public long Y { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    /// <summary>
    /// The coordinates and direction of the object
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CoordinateDirection : Coordinate
    {

        /// <summary>
        /// Direction the object is facing
        /// </summary>
        [Newtonsoft.Json.JsonProperty("direction", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Direction Direction { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Error
    {

        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Code { get; set; }

        [Newtonsoft.Json.JsonProperty("message", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Message { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [Newtonsoft.Json.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum Direction
    {

        [System.Runtime.Serialization.EnumMember(Value = @"N")]
        N = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"S")]
        S = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"E")]
        E = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"W")]
        W = 3,

    }


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765